export type BootstrapVariants = (
    "primary" |
    "d-primary" |
    "d-light-primary" |
    "d-secondary" |
    "d-info" |
    "d-light-gray" |
    "d-dark" |
    "secondary" |
    "success" |
    "warning" |
    "danger" |
    "info" |
    "light" |
    "dark" |
    "link" |
    "outline-primary" |
    "outline-secondary" |
    "outline-success" |
    "outline-warning" |
    "outline-danger" |
    "outline-info" |
    "outline-light" |
    "outline-dark" |
    "outline-d-primary" |
    "outline-d-light-primary" |
    "outline-d-secondary" |
    "outline-d-info" |
    "outline-d-light-gray" |
    "outline-d-dark" |
    "gray-100" |
    "gray-200" |
    "gray-300" |
    "gray-400" |
    "gray-500" |
    "gray-600" |
    "gray-700" |
    "gray-800" |
    "gray-900" |
    "red-100" |
    "red-200" |
    "red-300" |
    "red-400" |
    "red-500" |
    "red-600" |
    "red-700" |
    "red-800" |
    "red-900"
);